-- ========================================================================
-- Oracle AI Database 26ai SQL Firewall Setup (Production-Ready Demo Script)
-- Target: Dedicated PDB Instance
-- Execution Mode: Run as SYS AS SYSDBA using "Run Script (F5)"
-- Last Update: 01-Jun-2026
-- ========================================================================

-- 1. Setup Environment Controls for Full Query and Feedback Visibility

-- Force the client to display each SQL statement being executed
SET ECHO ON
-- Output execution summary messages (e.g., 'Table created')
SET FEEDBACK ON
-- Enable output routing for DBMS_OUTPUT messages
SET SERVEROUTPUT ON

-- 2. Target Container Routing
-- NOTE: Replace 'AHDB2605_PDB1;' with your actual PDB service name if different
ALTER SESSION SET CONTAINER = AHDB2605_PDB1;

-- 3. Core Security Principals (Users) Creation
CREATE USER AEGIS_APP IDENTIFIED BY "OracleFWDemo-123#";
CREATE USER luminaforge IDENTIFIED BY "OracleFWDemo-123#";

-- 4. Storage and Session Allocation
GRANT CONNECT, RESOURCE, CREATE SESSION TO AEGIS_APP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO luminaforge;
ALTER USER AEGIS_APP QUOTA UNLIMITED ON users;
ALTER USER luminaforge QUOTA UNLIMITED ON users;

-- 4b. Prevent demo account password expiry / lockout
-- The DEFAULT profile's finite PASSWORD_LIFE_TIME expires AEGIS_APP / luminaforge
-- after ~180 days, causing ORA-28001 in the apps. Disable password aging and
-- reuse limits so the long-lived demo accounts never expire (matches the live fix).
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_GRACE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_MAX UNLIMITED;

-- 5. Cross-Monitoring Authorization (Granting Dictionary View access to Aegis SOC)
-- Optimized using the Oracle 23c/26ai built-in monitoring role to eliminate view-name errors
GRANT SQL_FIREWALL_VIEWER TO AEGIS_APP;

-- 6. Context Switch for LuminaForge Data Layer Deployment
ALTER SESSION SET CURRENT_SCHEMA = luminaforge;

-- 7. Schema Architecture Construction (LuminaForge App Tables)
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username VARCHAR2(50), 
    password VARCHAR2(100), 
    role VARCHAR2(20)
);

CREATE TABLE portfolio (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 10000) PRIMARY KEY,
    user_id NUMBER, 
    symbol VARCHAR2(20), 
    quantity NUMBER, 
    avg_price NUMBER
);

CREATE TABLE transactions (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 10000) PRIMARY KEY,
    user_id NUMBER, 
    type VARCHAR2(20), 
    amount NUMBER, 
    asset VARCHAR2(40),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE luxury_items (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name VARCHAR2(100), 
    price NUMBER, 
    category VARCHAR2(50)
);

-- 8. Seed Data Population (generated from seed/luminaforge-demo-seed.json)
@@sql/luminaforge_demo_seed.sql

DECLARE
  l_users NUMBER;
  l_portfolio NUMBER;
  l_transactions NUMBER;
  l_luxury_items NUMBER;
BEGIN
  luminaforge.aegis_demo_seed.initialize(
    SYSTIMESTAMP AT TIME ZONE 'UTC',
    l_users, l_portfolio, l_transactions, l_luxury_items
  );
END;
/

COMMIT;

-- 9. Initialize and Boot up Oracle SQL Firewall Kernel Within the PDB
-- Explicit package resolution ensures invocation succeeds even under non-SYS current schema
EXEC SYS.DBMS_SQL_FIREWALL.ENABLE;

-- 10. Establish Traffic Capture Framework for Machine Learning Training Phase
BEGIN 
    SYS.DBMS_SQL_FIREWALL.CREATE_CAPTURE('AEGIS_APP', TRUE, TRUE); 
    SYS.DBMS_SQL_FIREWALL.CREATE_CAPTURE('luminaforge', TRUE, TRUE); 
END;
/

PROMPT === [SUCCESS] Oracle 26ai PDB SQL Firewall Initialization Infrastructure Ready ===
