import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import {
  readManifest,
  renderSeedSql,
  renderTransactionResetSql,
  validateManifest,
} from "../scripts/generate-luminaforge-demo-seed.mjs";
import {
  SOURCE_ANCHOR,
  rebaseTemporal,
} from "../scripts/demo-seed-time.mjs";

const manifest = readManifest();

test("canonical manifest validates and preserves stable IDs", () => {
  assert.doesNotThrow(() => validateManifest(structuredClone(manifest)));
  assert.equal(manifest.sourceAnchor, SOURCE_ANCHOR);
  assert.equal(manifest.users.find((user) => user.username === "demo_user").id, 1);
  assert.deepEqual(manifest.expectedCounts, {
    USERS: 27,
    PORTFOLIO: 40,
    TRANSACTIONS: 42,
    LUXURY_ITEMS: 20,
  });
});

test("manifest rejects duplicate IDs, broken references, and temporal drift", () => {
  const duplicate = structuredClone(manifest);
  duplicate.users[1].id = 1;
  assert.throws(() => validateManifest(duplicate), /duplicate IDs/);

  const broken = structuredClone(manifest);
  broken.portfolio[0].userId = 999999;
  assert.throws(() => validateManifest(broken), /broken user reference/);

  const temporal = structuredClone(manifest);
  temporal.temporalColumns = {};
  assert.throws(() => validateManifest(temporal), /undeclared temporal column/);
});

test("checked-in Oracle package is generated from the manifest", () => {
  const checkedIn = fs.readFileSync("sql/luminaforge_demo_seed.sql", "utf8");
  assert.equal(checkedIn, renderSeedSql(manifest));
  const executableSql = checkedIn.replace(/--.*$/gm, "");
  assert.doesNotMatch(executableSql, /\bCOMMIT\b|\bTRUNCATE\b/i);
  assert.ok(
    checkedIn.indexOf("DELETE FROM luminaforge.transactions") <
      checkedIn.indexOf("DELETE FROM luminaforge.users"),
  );
  assert.ok(
    checkedIn.indexOf("INSERT INTO luminaforge.users") <
      checkedIn.indexOf("INSERT INTO luminaforge.transactions"),
  );
});

test("setup and transaction reset consume generated canonical values", () => {
  const transactionReset = fs.readFileSync(
    "sql/luminaforge_reinit_transactions.sql",
    "utf8",
  );
  assert.equal(transactionReset, renderTransactionResetSql(manifest));
  assert.match(
    fs.readFileSync("Oracle_DB_Setup.sql", "utf8"),
    /@@sql\/luminaforge_demo_seed\.sql/,
  );
  assert.match(
    fs.readFileSync("luminaforge/scripts/reset-demo-data.sql", "utf8"),
    /@@\.\.\/\.\.\/sql\/luminaforge_demo_seed\.sql/,
  );
  assert.doesNotMatch(
    `${transactionReset}\n${fs.readFileSync("sql/luminaforge_demo_seed.sql", "utf8")}`,
    /\bDB_PASSWORD\b|\bDB_CONNECTION_STRING\b|BEGIN PRIVATE KEY/i,
  );
  const marketReseed = fs.readFileSync("scripts/reseed_market_vm.js", "utf8");
  assert.match(marketReseed, /seed\/luminaforge-demo-seed\.json/);
  assert.doesNotMatch(marketReseed, /Oracle Corp \(ORCL\)|Bitcoin \(BTC\)/);
});

test("identity migration reserves stable explicit seed IDs", () => {
  const migration = fs.readFileSync(
    "sql/luminaforge_demo_seed_identity_migration.sql",
    "utf8",
  );
  for (const table of ["USERS", "PORTFOLIO", "TRANSACTIONS", "LUXURY_ITEMS"]) {
    assert.match(migration, new RegExp(`migrate_identity\\('${table}'\\)`));
  }
  assert.match(migration, /GENERATED BY DEFAULT ON NULL AS IDENTITY/);
  assert.match(migration, /START WITH LIMIT VALUE/);
  const setup = fs.readFileSync("Oracle_DB_Setup.sql", "utf8");
  assert.equal(
    [...setup.matchAll(/GENERATED BY DEFAULT ON NULL AS IDENTITY/g)].length,
    4,
  );
  assert.match(
    fs.readFileSync("sql/luminaforge_demo_seed.sql", "utf8"),
    /users \(id, username, password, role\) VALUES \(1, 'demo_user'/,
  );
});

test("local disposable transaction fixture rolls back and is repeatable", () => {
  const original = {
    users: [{ id: 999, username: "mutated" }],
    portfolio: [{ id: 999, userId: 999 }],
    transactions: [{ id: 999, userId: 999, timestamp: "stale" }],
    luxuryItems: [{ id: 999, name: "extra" }],
    firewall: { enabled: true, violations: ["existing-log"] },
  };
  const reset = (state, anchor, failAfterDelete = false) => {
    const before = structuredClone(state);
    try {
      state.transactions = [];
      state.portfolio = [];
      state.luxuryItems = [];
      state.users = [];
      if (failAfterDelete) throw new Error("injected load failure");
      state.users = structuredClone(manifest.users);
      state.luxuryItems = structuredClone(manifest.luxuryItems);
      state.portfolio = structuredClone(manifest.portfolio);
      state.transactions = manifest.transactions.map((row) => ({
        ...structuredClone(row),
        timestamp: rebaseTemporal(anchor, row.temporal),
      }));
      return state;
    } catch (error) {
      Object.assign(state, before);
      throw error;
    }
  };

  const failed = structuredClone(original);
  assert.throws(
    () => reset(failed, "2027-03-31T12:34:56.789Z", true),
    /injected/,
  );
  assert.deepEqual(failed, original);

  const first = reset(
    structuredClone(original),
    "2027-03-31T12:34:56.789Z",
  );
  const second = reset(
    structuredClone(first),
    "2027-03-31T12:34:56.789Z",
  );
  assert.deepEqual(second, first);
  assert.deepEqual(first.firewall, original.firewall);
  assert.equal(first.users.find(({ username }) => username === "demo_user").id, 1);
  assert.ok(first.transactions.every(({ timestamp }) => timestamp.includes("2027")));
});

test("seed retains all LuminaForge benign and attack-point fixtures", () => {
  assert.ok(manifest.luxuryItems.some(({ name }) => name.includes("ORCL")));
  assert.ok(manifest.portfolio.some(({ userId }) => userId === 1));
  for (const userId of [3, 4, 5, 8, 9]) {
    assert.ok(manifest.transactions.some((row) => row.userId === userId));
  }
  assert.equal(manifest.users.length, 27);
  const grantSql = fs.readFileSync("Oracle_DB_Demo_Control_Grant.sql", "utf8");
  const resetBody = grantSql.slice(
    grantSql.lastIndexOf("  PROCEDURE initialize_demo_seed_data("),
    grantSql.indexOf("  END initialize_demo_seed_data;") +
      "  END initialize_demo_seed_data;".length,
  );
  assert.doesNotMatch(
    resetBody,
    /DBMS_SQL_FIREWALL|PURGE_LOG|DROP_CAPTURE|ALLOW_LIST/i,
  );
});

test("fixed anchor preserves exact historical and future durations", () => {
  const anchor = "2027-03-31T12:34:56.789Z";
  assert.equal(
    rebaseTemporal(anchor, {
      months: 0,
      days: -1,
      milliseconds: -12 * 60 * 60 * 1000,
      lastDayOfMonth: false,
    }),
    "2027-03-30T00:34:56.789Z",
  );
  assert.equal(
    rebaseTemporal(anchor, {
      months: 0,
      days: 10,
      milliseconds: 0,
      lastDayOfMonth: false,
    }),
    "2027-04-10T12:34:56.789Z",
  );
  assert.equal(rebaseTemporal(anchor, null), null);
});

test("calendar months preserve end-of-month and leap-year meaning", () => {
  const temporal = {
    months: -1,
    days: 0,
    milliseconds: 0,
    lastDayOfMonth: true,
  };
  assert.equal(
    rebaseTemporal("2028-03-31T12:34:56.789Z", temporal),
    "2028-02-29T12:34:56.789Z",
  );
  assert.equal(
    rebaseTemporal("2027-03-31T12:34:56.789Z", temporal),
    "2027-02-28T12:34:56.789Z",
  );
  assert.equal(
    rebaseTemporal("2027-05-30T12:34:56.789Z", {
      ...temporal,
      months: 1,
      lastDayOfMonth: false,
    }),
    "2027-06-30T12:34:56.789Z",
  );
});

test("aware instants are rebased in UTC across DST boundaries", () => {
  const instantWithOffset = "2027-03-14T01:30:00-05:00";
  assert.equal(
    rebaseTemporal(instantWithOffset, {
      months: 0,
      days: 0,
      milliseconds: 60 * 60 * 1000,
      lastDayOfMonth: false,
    }),
    "2027-03-14T07:30:00.000Z",
  );
});
