-- GENERATED by scripts/generate-luminaforge-demo-seed.mjs. DO NOT EDIT.
-- Source: seed/luminaforge-demo-seed.json
CREATE OR REPLACE PACKAGE luminaforge.aegis_demo_seed
AUTHID DEFINER
AS
  c_source_anchor CONSTANT VARCHAR2(24) := '2026-06-01T00:00:00.000Z';
  FUNCTION rebase_timestamp(
    p_target_anchor IN TIMESTAMP WITH TIME ZONE,
    p_months IN PLS_INTEGER,
    p_days IN NUMBER,
    p_milliseconds IN NUMBER,
    p_last_day_of_month IN NUMBER
  ) RETURN TIMESTAMP;
  PROCEDURE initialize(
    p_target_anchor IN TIMESTAMP WITH TIME ZONE,
    p_users OUT NUMBER,
    p_portfolio OUT NUMBER,
    p_transactions OUT NUMBER,
    p_luxury_items OUT NUMBER
  );
END aegis_demo_seed;
/

CREATE OR REPLACE PACKAGE BODY luminaforge.aegis_demo_seed
AS
  FUNCTION rebase_timestamp(
    p_target_anchor IN TIMESTAMP WITH TIME ZONE,
    p_months IN PLS_INTEGER,
    p_days IN NUMBER,
    p_milliseconds IN NUMBER,
    p_last_day_of_month IN NUMBER
  ) RETURN TIMESTAMP
  IS
    l_anchor TIMESTAMP := SYS_EXTRACT_UTC(p_target_anchor);
    l_midnight TIMESTAMP;
    l_clock INTERVAL DAY TO SECOND;
    l_month_date DATE;
    l_result TIMESTAMP;
  BEGIN
    IF p_target_anchor IS NULL THEN RETURN NULL; END IF;
    l_midnight := CAST(TRUNC(CAST(l_anchor AS DATE)) AS TIMESTAMP);
    l_clock := l_anchor - l_midnight;
    l_month_date := ADD_MONTHS(TRUNC(CAST(l_anchor AS DATE)), p_months);
    IF p_last_day_of_month = 1 THEN
      l_month_date := LAST_DAY(l_month_date);
    END IF;
    l_result := CAST(l_month_date AS TIMESTAMP) + l_clock;
    RETURN l_result
      + NUMTODSINTERVAL(p_days, 'DAY')
      + NUMTODSINTERVAL(p_milliseconds / 1000, 'SECOND');
  END rebase_timestamp;

  PROCEDURE initialize(
    p_target_anchor IN TIMESTAMP WITH TIME ZONE,
    p_users OUT NUMBER,
    p_portfolio OUT NUMBER,
    p_transactions OUT NUMBER,
    p_luxury_items OUT NUMBER
  )
  IS
    l_anchor TIMESTAMP WITH TIME ZONE :=
      COALESCE(p_target_anchor, SYSTIMESTAMP AT TIME ZONE 'UTC');
    l_broken_refs NUMBER;
    l_demo_user NUMBER;
    l_temporal_invalid NUMBER;
  BEGIN
    DELETE FROM luminaforge.transactions;
    DELETE FROM luminaforge.portfolio;
    DELETE FROM luminaforge.luxury_items;
    DELETE FROM luminaforge.users;

  INSERT INTO luminaforge.users (id, username, password, role) VALUES (1, 'demo_user', 'Wealth#2026!', 'premium');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (2, 'admin', 'Sup3rSecretAdmin#', 'admin');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (3, 'j.chen', 'As1aPacific!Mgr', 'premium');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (4, 'm.vanderbilt', 'OldM0ney$1899', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (5, 'r.sterling', 'L0nd0nDesk#FX', 'premium');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (6, 'sys_audit', '@udit$ystem26ai', 'audit');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (7, 'compliance_bot', 'C0mpl1@nce#RO', 'compliance');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (8, 'e.ashworth', 'Pvt#Bank1ng!', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (9, 'a.rothschild', 'HeritageF0nd!', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (10, 'trade_engine', 'Tr@deEngine#01', 'service');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (11, 'j.rockefeller', 'Dynast1c$Ofc!', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (12, 'risk_monitor', 'R1sk@M0n1tor!', 'risk');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (13, 'k.morgan', 'M0rg@nDesk#NY', 'premium');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (14, 's.blackwell', 'Blackw3ll$Ofc', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (15, 'l.dupont', 'DuP0ntHeir!', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (16, 'h.windsor', 'W1ndsorTrust#', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (17, 'p.gates_family', 'F@milyOff1ce!', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (18, 'n.buffett_trust', 'Trust3e#2026', 'premium');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (19, 'f.marsdorf', 'Marsd0rf$CH', 'premium');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (20, 'c.carnegie_heir', 'Carneg1e#Fund', 'vip');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (21, 'treasury_ops', 'Tr3asury@Ops', 'compliance');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (22, 'aml_scanner', 'AML$canner26', 'risk');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (23, 'settlement_svc', 'S3ttlement#01', 'service');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (24, 'wealth_api', 'We@lthAPI#Key', 'service');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (25, 'tax_filing_bot', 'TaxF1le$B0t', 'service');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (26, 'portfolio_rebal', 'Rebal#Engine2', 'service');
  INSERT INTO luminaforge.users (id, username, password, role) VALUES (27, 'kyc_reviewer', 'KYC_R3view!', 'audit');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (1, 'Oracle Corp (ORCL)', 141.5, 'stock');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (2, 'Microsoft Corp (MSFT)', 415.2, 'stock');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (3, 'JPMorgan Chase (JPM)', 198.6, 'stock');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (4, 'NVIDIA Corp (NVDA)', 924.6, 'stock');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (5, 'Apple Inc (AAPL)', 187.23, 'stock');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (6, 'US Treasury Bond 10Y', 101.8, 'bond');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (7, 'US Treasury Bill 6M', 99.4, 'bond');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (8, 'Investment Grade Corp Bond A', 102.3, 'bond');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (9, 'High Yield Corp Bond B', 95.7, 'bond');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (10, 'Vanguard S&P 500 ETF (VOO)', 490, 'etf');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (11, 'SPDR S&P 500 ETF (SPY)', 488, 'etf');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (12, 'Invesco QQQ Trust (QQQ)', 418, 'etf');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (13, 'Vanguard Total Market ETF (VTI)', 235.6, 'etf');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (14, 'Bitcoin (BTC)', 68450, 'crypto');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (15, 'Ethereum (ETH)', 3620, 'crypto');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (16, 'Solana (SOL)', 145, 'crypto');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (17, 'Gold Spot (XAU)', 2280, 'metal');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (18, 'Silver Spot (XAG)', 28.5, 'metal');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (19, '20+ Year Treasury ETF (TLT)', 94.2, 'bond_etf');
  INSERT INTO luminaforge.luxury_items (id, name, price, category) VALUES (20, 'Corporate Bond ETF (LQD)', 109.3, 'bond_etf');
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (1, 1, 'AAPL', 150, 185.5);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (2, 1, 'ORCL', 200, 138.3);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (3, 1, 'NVDA', 80, 620);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (4, 1, 'MSFT', 120, 380.25);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (5, 1, 'TSLA', 60, 195.8);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (6, 1, 'AMZN', 90, 178.4);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (7, 1, 'META', 100, 480);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (8, 1, 'GOOGL', 55, 168.9);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (9, 1, 'V', 130, 270.5);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (10, 1, 'JPM', 110, 198.6);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (11, 1, 'GS', 75, 460.1);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (12, 1, 'BRK.B', 40, 389.7);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (13, 1, 'SPY', 200, 490);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (14, 1, 'QQQ', 150, 420.3);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (15, 1, 'VTI', 180, 235.6);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (16, 1, 'GOLD', 500, 2280);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (17, 1, 'SILVER', 2000, 28.5);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (18, 1, 'BTC', 2, 58200);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (19, 1, 'ETH', 18, 3100);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (20, 1, 'SOL', 120, 145);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (21, 3, 'ORCL', 1200, 142.5);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (22, 3, 'BABA', 800, 88.2);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (23, 3, 'TSM', 600, 128.4);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (24, 3, 'FXI', 1500, 28.9);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (25, 4, 'BRK.B', 350, 392);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (26, 4, 'JPM', 900, 201.3);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (27, 4, 'V', 700, 272.8);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (28, 4, 'GLD', 2200, 218.5);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (29, 5, 'GS', 450, 455);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (30, 5, 'MS', 520, 102.4);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (31, 5, 'EUR/USD', 1, 1.08);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (32, 5, 'LVMH', 180, 785);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (33, 8, 'NVDA', 420, 615);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (34, 8, 'AAPL', 300, 188);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (35, 8, 'BTC', 12, 57500);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (36, 8, 'ETH', 85, 3050);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (37, 9, 'BRK.B', 800, 388.5);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (38, 9, 'SPY', 2500, 488);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (39, 9, 'QQQ', 1800, 418);
  INSERT INTO luminaforge.portfolio (id, user_id, symbol, quantity, avg_price) VALUES (40, 9, 'TLT', 3200, 94.2);
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (1, 1, 'BUY', 74000, 'ORCL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -30, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (2, 1, 'BUY', 49600, 'NVDA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -25, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (3, 1, 'SELL', 22800, 'TSLA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -22, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (4, 1, 'DIVIDEND', 3680, 'SPY', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -20, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (5, 1, 'BUY', 98000, 'META', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -18, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (6, 1, 'REBALANCE', 15000, 'VTI', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -15, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (7, 1, 'BUY', 27825, 'AAPL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -12, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (8, 1, 'INTEREST', 2190, 'JPM', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -10, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (9, 1, 'SELL', 18200, 'AMZN', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -8, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (10, 1, 'DIVIDEND', 1240, 'QQQ', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -5, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (11, 1, 'BUY', 53400, 'BTC', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -3, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (12, 1, 'TRANSFER', 5000, 'CASH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (13, 3, 'WIRE', 4750000, 'WIRE-APAC', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -14, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (14, 3, 'BUY', 890000, 'ORCL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -9, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (15, 4, 'WIRE', 12300000, 'WIRE-US', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -11, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (16, 4, 'SETTLE', 3200000, 'USD-SETTLE', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -6, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (17, 5, 'FX', 2100000, 'EUR/USD', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -7, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (18, 5, 'SELL', 780000, 'GS', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -3, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (19, 8, 'WIRE', 9500000, 'WIRE-PRIVATE', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -15, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (20, 8, 'BUY', 1840000, 'NVDA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -4, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (21, 9, 'SETTLE', 18750000, 'SETTLE-HF', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -20, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (22, 9, 'BUY', 5600000, 'BRK.B', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -1, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (23, 3, 'SELL', 412000, 'BABA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -13, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (24, 3, 'DIVIDEND', 28500, 'TSM', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -10, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (25, 3, 'BUY', 156000, 'FXI', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -5, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (26, 3, 'TRANSFER', 89000, 'CASH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (27, 4, 'BUY', 640000, 'JPM', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -12, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (28, 4, 'DIVIDEND', 42000, 'V', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -8, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (29, 4, 'SELL', 288000, 'GLD', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -4, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (30, 4, 'INTEREST', 18500, 'BRK.B', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -1, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (31, 5, 'BUY', 925000, 'LVMH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -11, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (32, 5, 'WIRE', 1800000, 'WIRE-EU', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -9, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (33, 5, 'DIVIDEND', 31000, 'MS', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -5, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (34, 5, 'REBALANCE', 142000, 'GS', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (35, 8, 'SELL', 520000, 'AAPL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -13, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (36, 8, 'BUY', 890000, 'BTC', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -10, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (37, 8, 'TRANSFER', 250000, 'CASH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -6, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (38, 8, 'DIVIDEND', 48000, 'NVDA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (39, 9, 'SELL', 3200000, 'SPY', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -14, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (40, 9, 'BUY', 1450000, 'QQQ', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -8, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (41, 9, 'REBALANCE', 680000, 'TLT', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -4, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (42, 9, 'WIRE', 4200000, 'WIRE-HF', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -1, 0, 0));

    SELECT COUNT(*) INTO p_users FROM luminaforge.users;
    SELECT COUNT(*) INTO p_portfolio FROM luminaforge.portfolio;
    SELECT COUNT(*) INTO p_transactions FROM luminaforge.transactions;
    SELECT COUNT(*) INTO p_luxury_items FROM luminaforge.luxury_items;

    IF p_users != 27
       OR p_portfolio != 40
       OR p_transactions != 42
       OR p_luxury_items != 20 THEN
      RAISE_APPLICATION_ERROR(-20061, 'Demo seed row-count validation failed');
    END IF;

    SELECT COUNT(*) INTO l_broken_refs
    FROM (
      SELECT user_id FROM luminaforge.portfolio
      UNION ALL
      SELECT user_id FROM luminaforge.transactions
    ) child
    WHERE NOT EXISTS (
      SELECT 1 FROM luminaforge.users parent WHERE parent.id = child.user_id
    );
    IF l_broken_refs != 0 THEN
      RAISE_APPLICATION_ERROR(-20062, 'Demo seed referential validation failed');
    END IF;
    SELECT COUNT(*) INTO l_demo_user
    FROM luminaforge.users
    WHERE id = 1 AND username = 'demo_user';
    IF l_demo_user != 1 THEN
      RAISE_APPLICATION_ERROR(-20063, 'Demo seed identity validation failed');
    END IF;
    SELECT COUNT(*) INTO l_temporal_invalid
    FROM luminaforge.transactions
    WHERE timestamp IS NULL
       OR timestamp >= CAST(SYS_EXTRACT_UTC(l_anchor) AS TIMESTAMP)
       OR timestamp < rebase_timestamp(l_anchor, 0, -30, 0, 0);
    IF l_temporal_invalid != 0 THEN
      RAISE_APPLICATION_ERROR(-20068, 'Demo seed temporal validation failed');
    END IF;
    -- Caller owns COMMIT/ROLLBACK so the complete reset stays atomic.
  END initialize;
END aegis_demo_seed;
/
