-- GENERATED by scripts/generate-luminaforge-demo-seed.mjs. DO NOT EDIT.
-- Transaction-only reset used by the existing Break-Glass control.
CREATE OR REPLACE PROCEDURE luminaforge.aegis_demo_reinit_transactions
AUTHID DEFINER
AS
  l_anchor TIMESTAMP WITH TIME ZONE := SYSTIMESTAMP AT TIME ZONE 'UTC';
  l_count NUMBER;
BEGIN
  DELETE FROM luminaforge.transactions;
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (1, 1, 'BUY', 74000, 'ORCL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -30, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (2, 1, 'BUY', 49600, 'NVDA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -25, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (3, 1, 'SELL', 22800, 'TSLA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -22, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (4, 1, 'DIVIDEND', 3680, 'SPY', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -20, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (5, 1, 'BUY', 98000, 'META', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -18, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (6, 1, 'REBALANCE', 15000, 'VTI', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -15, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (7, 1, 'BUY', 27825, 'AAPL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -12, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (8, 1, 'INTEREST', 2190, 'JPM', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -10, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (9, 1, 'SELL', 18200, 'AMZN', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -8, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (10, 1, 'DIVIDEND', 1240, 'QQQ', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -5, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (11, 1, 'BUY', 53400, 'BTC', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -3, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (12, 1, 'TRANSFER', 5000, 'CASH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (13, 3, 'WIRE', 4750000, 'WIRE-APAC', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -14, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (14, 3, 'BUY', 890000, 'ORCL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -9, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (15, 4, 'WIRE', 12300000, 'WIRE-US', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -11, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (16, 4, 'SETTLE', 3200000, 'USD-SETTLE', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -6, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (17, 5, 'FX', 2100000, 'EUR/USD', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -7, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (18, 5, 'SELL', 780000, 'GS', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -3, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (19, 8, 'WIRE', 9500000, 'WIRE-PRIVATE', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -15, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (20, 8, 'BUY', 1840000, 'NVDA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -4, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (21, 9, 'SETTLE', 18750000, 'SETTLE-HF', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -20, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (22, 9, 'BUY', 5600000, 'BRK.B', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -1, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (23, 3, 'SELL', 412000, 'BABA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -13, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (24, 3, 'DIVIDEND', 28500, 'TSM', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -10, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (25, 3, 'BUY', 156000, 'FXI', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -5, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (26, 3, 'TRANSFER', 89000, 'CASH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (27, 4, 'BUY', 640000, 'JPM', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -12, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (28, 4, 'DIVIDEND', 42000, 'V', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -8, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (29, 4, 'SELL', 288000, 'GLD', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -4, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (30, 4, 'INTEREST', 18500, 'BRK.B', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -1, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (31, 5, 'BUY', 925000, 'LVMH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -11, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (32, 5, 'WIRE', 1800000, 'WIRE-EU', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -9, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (33, 5, 'DIVIDEND', 31000, 'MS', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -5, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (34, 5, 'REBALANCE', 142000, 'GS', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (35, 8, 'SELL', 520000, 'AAPL', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -13, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (36, 8, 'BUY', 890000, 'BTC', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -10, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (37, 8, 'TRANSFER', 250000, 'CASH', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -6, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (38, 8, 'DIVIDEND', 48000, 'NVDA', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -2, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (39, 9, 'SELL', 3200000, 'SPY', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -14, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (40, 9, 'BUY', 1450000, 'QQQ', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -8, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (41, 9, 'REBALANCE', 680000, 'TLT', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -4, 0, 0));
  INSERT INTO luminaforge.transactions (id, user_id, type, amount, asset, timestamp) VALUES (42, 9, 'WIRE', 4200000, 'WIRE-HF', luminaforge.aegis_demo_seed.rebase_timestamp(l_anchor, 0, -1, 0, 0));
  SELECT COUNT(*) INTO l_count FROM luminaforge.transactions;
  IF l_count != 42 THEN
    RAISE_APPLICATION_ERROR(-20067, 'Transaction seed row-count validation failed');
  END IF;
  COMMIT;
END aegis_demo_reinit_transactions;
/
