-- One-time/idempotent install migration. This DDL is never run by the web action.
-- It permits explicit stable seed IDs and moves each backing identity sequence
-- above the table's current maximum value.
ALTER SESSION SET CONTAINER = AHDB2605_PDB1;

DECLARE
  l_generation_type VARCHAR2(30);

  PROCEDURE migrate_identity(p_table IN VARCHAR2) IS
  BEGIN
    SELECT generation_type
      INTO l_generation_type
      FROM dba_tab_identity_cols
     WHERE owner = 'LUMINAFORGE'
       AND table_name = p_table
       AND column_name = 'ID';

    IF l_generation_type = 'ALWAYS' THEN
      EXECUTE IMMEDIATE
        'ALTER TABLE luminaforge.' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_table) ||
        ' MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY';
    END IF;

    EXECUTE IMMEDIATE
      'ALTER TABLE luminaforge.' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_table) ||
      ' MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE)';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20064, 'Missing identity: LUMINAFORGE.' || p_table || '.ID');
  END;
BEGIN
  migrate_identity('USERS');
  migrate_identity('PORTFOLIO');
  migrate_identity('TRANSACTIONS');
  migrate_identity('LUXURY_ITEMS');
END;
/
